[package]
name = "refuzzer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rbpf = { path = "../rbpf" }
faerie = "0.16.0"
target-lexicon = "0.11"
anyhow = "1.0.69"
rand = "0.8.5"
